java_library(
    name = "toptracks",
        srcs = glob(["*.java"]),
        deps = [
                                      "//3rdparty/jvm/com/spotify:apollo-api",
                                      "//src/main/java/com/asaenf/exception:exception",
                                                        "//3rdparty/jvm/com/spotify:apollo-core",
                                                        "//3rdparty/jvm/com/spotify:apollo-api-impl",
                                                        "//3rdparty/jvm/com/spotify:apollo-environment",
                                                        "//3rdparty/jvm/com/spotify:apollo-metrics",
                                                        "//3rdparty/jvm/com/spotify:apollo-okhttp-client",
                                                        "//3rdparty/jvm/com/spotify:apollo-route",
                                                        "//3rdparty/jvm/com/spotify/metrics:semantic-metrics-api",
                                                        "//3rdparty/jvm/com/spotify/metrics:semantic-metrics-core",
                                                             "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-databind",
                                                              "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-annotations",
                                                               "//3rdparty/jvm/com/fasterxml/jackson/core:jackson-core",
                                                              "//3rdparty/jvm/com/fasterxml/jackson/dataformat:jackson-dataformat-yaml",
                                                               "//3rdparty/jvm/com/fasterxml/jackson/datatype:jackson-datatype-guava",
                                                             "//3rdparty/jvm/com/fasterxml/jackson/datatype:jackson-datatype-joda",

                                                                "//3rdparty/jvm/ch/qos/logback:logback-classic",
                                                                "//3rdparty/jvm/ch/qos/logback:logback-core",
                                                                "//3rdparty/jvm/com/squareup/okio:okio",
                                                                "//3rdparty/jvm/org/slf4j:slf4j-api"
              ],
         visibility = ["//src/main/java/com/asaenf:__subpackages__",
                       "//src/test/java/com/asaenf:__subpackages__"]
)