package com.asaenf.top;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.List;
import org.junit.Before;
import org.junit.Test;

public class JsonUserTopTracksResponseConverterTest {

  String sampleResp = "{\n"
                      + "  \"items\": [\n"
                      + "    {\n"
                      + "      \"album\": {\n"
                      + "        \"album_type\": \"ALBUM\",\n"
                      + "        \"artists\": [\n"
                      + "          {\n"
                      + "            \"external_urls\": {\n"
                      + "              \"spotify\": \"https://open.spotify.com/artist/7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "            },\n"
                      + "            \"href\": \"https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "            \"id\": \"7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "            \"name\": \"Arctic Monkeys\",\n"
                      + "            \"type\": \"artist\",\n"
                      + "            \"uri\": \"spotify:artist:7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "          }\n"
                      + "        ],\n"
                      + "        \"external_urls\": {\n"
                      + "          \"spotify\": \"https://open.spotify.com/album/7v6FNgLDS8KmaWA1amUtqe\"\n"
                      + "        },\n"
                      + "        \"href\": \"https://api.spotify.com/v1/albums/7v6FNgLDS8KmaWA1amUtqe\",\n"
                      + "        \"id\": \"7v6FNgLDS8KmaWA1amUtqe\",\n"
                      + "        \"images\": [\n"
                      + "          {\n"
                      + "            \"height\": 640,\n"
                      + "            \"url\": \"https://i.scdn.co/image/47b1fe9ae4c4240aaf4ba038a8d99b4b177bd437\",\n"
                      + "            \"width\": 640\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"height\": 300,\n"
                      + "            \"url\": \"https://i.scdn.co/image/b1a4889b1c580bb8a4f95d2c811dd5b2629324c9\",\n"
                      + "            \"width\": 300\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"height\": 64,\n"
                      + "            \"url\": \"https://i.scdn.co/image/aa43cfc1ea38417f93c4bd1d030640cd2e62f3b1\",\n"
                      + "            \"width\": 64\n"
                      + "          }\n"
                      + "        ],\n"
                      + "        \"name\": \"Tranquility Base Hotel & Casino\",\n"
                      + "        \"release_date\": \"2018-05-10\",\n"
                      + "        \"release_date_precision\": \"day\",\n"
                      + "        \"type\": \"album\",\n"
                      + "        \"uri\": \"spotify:album:7v6FNgLDS8KmaWA1amUtqe\"\n"
                      + "      },\n"
                      + "      \"artists\": [\n"
                      + "        {\n"
                      + "          \"external_urls\": {\n"
                      + "            \"spotify\": \"https://open.spotify.com/artist/7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "          },\n"
                      + "          \"href\": \"https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "          \"id\": \"7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "          \"name\": \"Arctic Monkeys\",\n"
                      + "          \"type\": \"artist\",\n"
                      + "          \"uri\": \"spotify:artist:7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "        }\n"
                      + "      ],\n"
                      + "      \"disc_number\": 1,\n"
                      + "      \"duration_ms\": 271613,\n"
                      + "      \"explicit\": false,\n"
                      + "      \"external_ids\": {\n"
                      + "        \"isrc\": \"GBCEL1800173\"\n"
                      + "      },\n"
                      + "      \"external_urls\": {\n"
                      + "        \"spotify\": \"https://open.spotify.com/track/7aiKdAM9WYW3GzWSA9OXIl\"\n"
                      + "      },\n"
                      + "      \"href\": \"https://api.spotify.com/v1/tracks/7aiKdAM9WYW3GzWSA9OXIl\",\n"
                      + "      \"id\": \"7aiKdAM9WYW3GzWSA9OXIl\",\n"
                      + "      \"is_local\": false,\n"
                      + "      \"is_playable\": true,\n"
                      + "      \"name\": \"Batphone\",\n"
                      + "      \"popularity\": 53,\n"
                      + "      \"preview_url\": \"https://p.scdn.co/mp3-preview/c05dc9b22471682a1ca545947c8c0c47911a4832?cid=null\",\n"
                      + "      \"track_number\": 10,\n"
                      + "      \"type\": \"track\",\n"
                      + "      \"uri\": \"spotify:track:7aiKdAM9WYW3GzWSA9OXIl\"\n"
                      + "    },\n"
                      + "    {\n"
                      + "      \"album\": {\n"
                      + "        \"album_type\": \"ALBUM\",\n"
                      + "        \"artists\": [\n"
                      + "          {\n"
                      + "            \"external_urls\": {\n"
                      + "              \"spotify\": \"https://open.spotify.com/artist/7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "            },\n"
                      + "            \"href\": \"https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "            \"id\": \"7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "            \"name\": \"Arctic Monkeys\",\n"
                      + "            \"type\": \"artist\",\n"
                      + "            \"uri\": \"spotify:artist:7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "          }\n"
                      + "        ],\n"
                      + "        \"external_urls\": {\n"
                      + "          \"spotify\": \"https://open.spotify.com/album/7v6FNgLDS8KmaWA1amUtqe\"\n"
                      + "        },\n"
                      + "        \"href\": \"https://api.spotify.com/v1/albums/7v6FNgLDS8KmaWA1amUtqe\",\n"
                      + "        \"id\": \"7v6FNgLDS8KmaWA1amUtqe\",\n"
                      + "        \"images\": [\n"
                      + "          {\n"
                      + "            \"height\": 640,\n"
                      + "            \"url\": \"https://i.scdn.co/image/47b1fe9ae4c4240aaf4ba038a8d99b4b177bd437\",\n"
                      + "            \"width\": 640\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"height\": 300,\n"
                      + "            \"url\": \"https://i.scdn.co/image/b1a4889b1c580bb8a4f95d2c811dd5b2629324c9\",\n"
                      + "            \"width\": 300\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"height\": 64,\n"
                      + "            \"url\": \"https://i.scdn.co/image/aa43cfc1ea38417f93c4bd1d030640cd2e62f3b1\",\n"
                      + "            \"width\": 64\n"
                      + "          }\n"
                      + "        ],\n"
                      + "        \"name\": \"Tranquility Base Hotel & Casino\",\n"
                      + "        \"release_date\": \"2018-05-10\",\n"
                      + "        \"release_date_precision\": \"day\",\n"
                      + "        \"type\": \"album\",\n"
                      + "        \"uri\": \"spotify:album:7v6FNgLDS8KmaWA1amUtqe\"\n"
                      + "      },\n"
                      + "      \"artists\": [\n"
                      + "        {\n"
                      + "          \"external_urls\": {\n"
                      + "            \"spotify\": \"https://open.spotify.com/artist/7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "          },\n"
                      + "          \"href\": \"https://api.spotify.com/v1/artists/7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "          \"id\": \"7Ln80lUS6He07XvHI8qqHH\",\n"
                      + "          \"name\": \"Arctic Monkeys\",\n"
                      + "          \"type\": \"artist\",\n"
                      + "          \"uri\": \"spotify:artist:7Ln80lUS6He07XvHI8qqHH\"\n"
                      + "        }\n"
                      + "      ],\n"
                      + "      \"disc_number\": 1,\n"
                      + "      \"duration_ms\": 158040,\n"
                      + "      \"explicit\": false,\n"
                      + "      \"external_ids\": {\n"
                      + "        \"isrc\": \"GBCEL1800166\"\n"
                      + "      },\n"
                      + "      \"external_urls\": {\n"
                      + "        \"spotify\": \"https://open.spotify.com/track/2HbYLDA1SigY1ilC94ieVu\"\n"
                      + "      },\n"
                      + "      \"href\": \"https://api.spotify.com/v1/tracks/2HbYLDA1SigY1ilC94ieVu\",\n"
                      + "      \"id\": \"2HbYLDA1SigY1ilC94ieVu\",\n"
                      + "      \"is_local\": false,\n"
                      + "      \"is_playable\": true,\n"
                      + "      \"name\": \"American Sports\",\n"
                      + "      \"popularity\": 55,\n"
                      + "      \"preview_url\": \"https://p.scdn.co/mp3-preview/aa923f7fc63e04db25d28dbe6737614591bc9e1d?cid=null\",\n"
                      + "      \"track_number\": 3,\n"
                      + "      \"type\": \"track\",\n"
                      + "      \"uri\": \"spotify:track:2HbYLDA1SigY1ilC94ieVu\"\n"
                      + "    }\n"
                      + "  ],\n"
                      + "  \"total\": 50,\n"
                      + "  \"limit\": 2,\n"
                      + "  \"offset\": 5,\n"
                      + "  \"href\": \"https://api.spotify.com/v1/me/top/tracks?limit=2&offset=5\",\n"
                      + "  \"previous\": \"https://api.spotify.com/v1/me/top/tracks?limit=2&offset=3\",\n"
                      + "  \"next\": \"https://api.spotify.com/v1/me/top/tracks?limit=2&offset=7\"\n"
                      + "}";


  JsonUserTopTracksResponseConverter converter;

  @Before
  public void setUp(){
    converter = new JsonUserTopTracksResponseConverter(new ObjectMapper());
  }

  @Test
  public void jsonResponseParsedCorrectly() throws IOException {
    List<String> topIds = converter.getTopTrackUris(sampleResp);
    assertThat(topIds).hasSize(2);
    assertThat(topIds).containsExactlyInAnyOrder("spotify:track:7aiKdAM9WYW3GzWSA9OXIl",
        "spotify:track:2HbYLDA1SigY1ilC94ieVu");
  }
}

