java_library(
    name = "exception",
      srcs = glob(["*.java"]),
        deps = [
              ],
         visibility = ["//src/main/java/com/asaenf:__subpackages__",
                       "//src/test/java/com/asaenf:__subpackages__"]
)